# permissions for end users to edit reports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: report-editor-role
rules:
- apiGroups:
  - default.report.tjkj.com
  resources:
  - reports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - default.report.tjkj.com
  resources:
  - reports/status
  verbs:
  - get
